'use strict';

module.exports = {
    MONGODB_USERNAME: process.env.MONGODB_USERNAME,
    MONGODB_PASSWORD: process.env.MONGODB_PASSWORD,
    MONGODB_ENDPOINT: process.env.MONGODB_ENDPOINT,
    AWS_REGION: process.env.AWS_REGION,
    DYNAMODB_TABLE_NAME: process.env.DYNAMODB_TABLE_NAME,
    MONGODB_COLLECTION_NAME: process.env.MONGODB_COLLECTION_NAME,
    MONGODB_DATABASE_NAME: process.env.MONGODB_DATABASE_NAME
};